name: Deploy Infrastructure
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/terragrunt
          key: terragrunt-${{ runner.os }}-${{ hashFiles('**/*.hcl') }}
          restore-keys: |
            terragrunt-${{ runner.os }}-
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Cachix
        uses: cachix/cachix-action@v16
        with:
          name: terragrunt-dev-env
          skipPush: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::767140398543:role/github-oidc-terraform
          aws-region: eu-central-1
      - name: Validate infrastructure
        run: nix run .#validate
      - name: Apply infrastructure
        run: nix run .#apply
