# This workflow is provided as an example and is not intended to run automatically.
# To enable it, replace `on:` with a valid trigger like `push`, `pull_request`, or `workflow_dispatch`.

name: Deploy Infrastructure
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Nix Quick Install
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::767140398543:role/github-oidc-terraform
          aws-region: eu-central-1
      - name: Validate infrastructure
        run: nix run .#validate
      - name: Apply infrastructure
        run: nix run .#apply
